runtime: go
api_version: go1

service: consumer

handlers:
- url: /push
  script: _go_app
- url: /initDataset
  script: _go_app

env_variables:
  GOOGLE_CLOUD_PROJECT: delacon-dt-dev
  PUBSUB_TOPIC: data-transfer
  PUBSUB_SUBS: data-transfer-subs
  DATASET_ID: dt_event_stream
  EVENTS_TABLE_ID: events
